api:
  id: "19355698"
listener:
  port : "8081"
search-papi:
  host: "email-sapi-a0y7fb.5sc6y6-3.usa-e2.cloudhub.io"
  base-path: "api"
  request_path: "books"
  client_id: "351532e288024104afe8976ceec7d3be"
  client_secret: "70c9555caAb248729d3e2ceabc91f9bB"