api:
  id: "19355698"

listener:
  port : "8081"

search-papi:
  protocol: "HTTP"
  host: "localhost"
  port: "8082"
  base-path: "api"
  request_path: "search"
  client_id: "351532e288024104afe8976ceec7d3be"
  client_secret: "70c9555caAb248729d3e2ceabc91f9bB"